export const RECEIVE_ADDRESS = 'receive_address' // 接收地址信息
export const RECEIVE_CATEGORYS = 'receive_categorys' // 接收分类数组
export const RECEIVE_SHOPS = 'receive_shops' // 接收商家数组
export const RECEIVE_USER = 'receive_user'  //接收用户信息
export const RESET_USER = 'reset_user' //退出用户登录
export const RECEIVE_GOODS = 'receive_goods' //接收shop中的商品信息
export const RECEIVE_INFO = 'receive_info' //接收shop中的商家信息
export const RECEIVE_RATINGS = 'receive_ratings' //接收shop中的评分信息
export const INCREMENT_FOOD_COUNT = 'increment_food_count' //购物车加
export const DECREMENT_FOOD_COUNT = 'decrement_food_count'  //购物车减
export const CLEAR_CART = 'clear_cart'  //清空购物车列表
